### ISSUE TITLE
How do you fix autoLoot and bump fire?

### ISSUE THREAD

**Issue by ThanksMrSotarks** [zbot473/SurvivHacks#44]
Got the same issue after I deob the codes and fixed the vars, autoLoot and bump fire stopped working. Do I need to change the values somewhere in init.js or background.js? @zbot473 @Kalaborative @PowerOfUniverse

**Comment by alexvornoffice** [comment]
Thanks for update! I will try very soon to see if it works..

**Comment by alexvornoffice** [comment]
I tried the new cheat and the game freezes after some time of play... I don't know why, I can not replicate with cheat disabled... so it is hax problem I think...

**Comment by Exerciz** [comment]
Fix it please

**Comment by Kalaborative** [comment]
I'll look into it

**Comment by alexvornoffice** [comment]
The "Play Duo" mode works but Halloween map freezes after one minute of playtime, what could it be? :(

**Comment by zbot473** [comment]
I fixed it.

**Comment by zbot473** [comment]
You need to look in the prototype

**Comment by alexvornoffice** [comment]
The game still freezes for me, I will try again to see if it occurs...

**Comment by alexvornoffice** [comment]
Update: yeah! unplayable! I played 2 times and the same problem happens every time.
